name: download-music

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: download
        run: |
          curl -Lf  https://github.com/spotDL/spotify-downloader/releases/download/v4.5.0/spotdl-4.5.0-linux > spotdl
          chmod 777 spotdl
          ./spotdl --download-ffmpeg
          ./spotdl --download-deno
          ./spotdl download https://open.spotify.com/playlist/37i9dQZEVXbLwpL8TjsxOG
          ls -la